language: python

addons:
  apt:
    packages:
      - gcc  # numpy/scipy
      - gfortran  # numpy/scipy
      - libblas-dev  # numpy/scipy
      - liblapack-dev  # numpy/scipy
      - swig  # m2crypto

matrix:
  include:
    - python: 2.6
      env: PRE=""
    - python: 2.7
      env: PRE=""
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"
  allow_failures:
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"

before_install:
  - pip install -q --upgrade pip
  - pip install -q ${PRE} coveralls "pytest>=2.8" unittest2
  # need to install astropy 1.1 specifically for py26
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.6' ]]; then pip install "astropy==1.1"; fi

install:
  - pip install ${PRE} -r requirements.txt
  - python setup.py build

script:
  - coverage run --source=omicron --omit="omicron/tests/*,omicron/_version.py" -m py.test -v omicron/
  - pip install .

after_success:
  - coveralls

cache:
  - pip
  - apt
